### ISSUE TITLE
Please add instances for Alternative, MonadPlus and MonadFail

### ISSUE THREAD

**Issue by lspitzner** [nikita-volkov/deque#4]
I have a PR for the first two sitting for quite some time already :-/

Nonetheless thanks for maintaining this library.

**Comment by nikita-volkov** [comment]
The PR is now fixed and merged. However a MonadFail instance would not make sense

**Comment by lspitzner** [comment]
Thanks!

Ah I see, there currently also is no implementation for `Monad.fail` - so my client-side code can currently crash, good to know. Can I convince you to reconsider, for consistency with other containers:

~~~~.hs
do { True <- pure False; pure () } :: [()]     -- []
do { True <- pure False; pure () } :: Maybe () -- Nothing
do { True <- pure False; pure () } :: Deque () -- Exception: Pattern match failure

-- similarly with MonadComprehensions:

[ () | True <- pure False ] :: [()]     -- []
[ () | True <- pure False ] :: Maybe () -- Nothing
[ () | True <- pure False ] :: Deque () -- Exception: Pattern match failure
~~~~

**Comment by nikita-volkov** [comment]
Okay. Done :)

**Comment by lspitzner** [comment]
unfortunately your fix only works with ghc-8.6+, while with 8.0-8.4 you still get pattern-match-failure. See #5. I guess I should have linked the PR here; I assumed you'd get a notification.
